services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: cnpj
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  cnpj-data-pipeline:
    build:
      context: ../..
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ../../temp:/app/temp
      - ../../logs:/app/logs
    environment:
      DATABASE_BACKEND: postgresql
      PROCESSING_STRATEGY: auto
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: cnpj
      DB_USER: postgres
      DB_PASSWORD: postgres
      BATCH_SIZE: 50000
      MAX_MEMORY_PERCENT: 80
      DEBUG: "false"
    restart: unless-stopped

volumes:
  postgres_data:
